version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  # GitHub Actions used in workflows
  # TODO: enable after v5 stable release
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"
