name: Bump version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Download the latest zip
        uses: carlosperate/download-file-action@v2
        with:
          file-url: 'https://downloads.crowdin.com/cli/v3/crowdin-cli.zip'

      - name: Generate shasum
        id: shasum
        run: echo hash=$(shasum -a 256 crowdin-cli.zip | cut -f 1 -d " ") >> $GITHUB_OUTPUT

      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --define CHECKSUM=${{ steps.shasum.outputs.hash }}
