name: Bump version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
        run: |
          npx semantic-release
          npx semantic-release --version
