name: Documentation Release

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: website/package-lock.json

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate Docs
        run: bun run docs

      - name: Install website dependencies
        working-directory: website
        run: npm ci

      - name: Build Website
        working-directory: website
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          branch: gh-pages
          folder: website/build
